### ISSUE TITLE
Few remarks after review frontend part

### ISSUE THREAD

**Issue by rkoziol** [voinar/mern_photographer-portfolio-ecommerce-site#1]
Nie wiem, na ile jest to in progress, ale Oskar mowil ze bedziesz zadowolony z feedbacku, to daje:

- powtarzaja Ci sie properties dla jednego elementu w stylach np.: display https://github.com/voinar/mern_photographer-portfolio-ecommerce-site/blob/master/photographer-portfolio-frontend/src/components/styles/_Alert.scss;

- dobrze jest miec zamkniete / wyciagniete kolory, rozmiary czcionek etc do zmiennych. Bedzie CI pozniej latwiej edytowac pliczki;

- sporo latwiej mialbys po zainstalowaniu jakiegos linta do stylu np.: stylelint;

- zapiski takie jak:

```
const About = () => {
  return (

```

mozesz skracac do:

`const About = () => (<div>...);`

- zamiast miec duzo importow z jednej sciezki, zrob plik index i tam zaimportuj sobie wszystko z danego katalogu, a pozniej index importuj do poszczegolnych page/components

tutaj masz przyklad, co moze zostac skrocone:

```
import img0 from '../img/about/about-1.jpg';
import img1 from '../img/about/about-2.jpg';
import img2 from '../img/about/about-3.jpg';
import img3 from '../img/about/about-4.jpg';
```

- rzeczy takie jak numer telefonu, mail etc (href="mailto:kporadafoto@gmail.com") mozesz zamknac w pliku env i tam trzymac, ulatwi Ci to trzymanie jednego source of true i pozniejsze edytowanie, gdyby cos sie zmienilo

````
export const getError = (error) => {
  return error.response && error.response.data.message
    ? error.response.data.message
    : error.message;
};
````

w powyzszym kodzie doczytaj sobie o Optional Chaining Operator w JS, moze byc przydatny w tym wypadku i na przyszlosc :)

```
 useEffect(() => {
    import('react-facebook-pixel')
      .then((x) => x.default)
      .then((ReactPixel) => {
        ReactPixel.init(facebookPixelId);
        ReactPixel.pageView();

        // Routes.events.on('routeChangeComplete', () => {
        // ReactPixel.pageView();
        // });
      });
  });
```

importy trzymaj zawsze u gory pliku

```
  //run actions on every state update
  useEffect(() => {
    console.log('store updated');
    localStorage.setItem('cartItems', JSON.stringify(state.cart.cartItems));
  }, [state]);
```

taki effect moze byc ciezki dla aplikacji, na pierwszy rzut mozesz to zamkna tylko do cartItems

```
 <Route path="/" element={<SectionWelcome />} />
          <Route path="/witaj" element={<SectionWelcome />} />
          <Route path="/:category" element={<SectionContent />} />
          <Route path="/o%20mnie" element={<About />} />
          <Route path="/sklep" element={<Shop />} />
          <Route path="/album/:album" element={<Album />} />
          <Route path="/experiments" element={<Experiments />} />
          <Route path="/koszyk" element={<Cart />} />
          <Route path="/logowanie" element={<SignIn />} />
          <Route path="/podsumowanie" element={<Checkout />} />
          <Route path="/zamawiam" element={<OrderForm />} />
          <Route path="/twojezakupy" element={<Success />} />
          <Route path="/regulamin" element={<TermsConditions />} />
          <Route path="/cookies" element={<Cookies />} />
```
 takie cos najlepiej zamknac w osobnym pliku, ktory definiuje routing i po prostu mapowac juz w docelowym miejscu
 
 https://github.com/voinar/mern_photographer-portfolio-ecommerce-site/blob/master/photographer-portfolio-frontend/src/components/AlbumCard.jsx - ta destrujkcja propsow moze byc smialo uzyta wyzej, dzieki temu zyskasz na czytelnosci

**Comment by voinar** [comment]
Dzięki Radek, przyda się :) 

Co do zaawansowania, projekt jest gdzieś za połową drogi, więc faktycznie w css będzie trochę sprzątania. Style fontów już importuję z _variables.scss - obecnie wypracowuję sobie wyczucie tego jaki powinien być zakres stosowania zmiennych. Rzeczy typu zaokrąglenia box'ów czy style ramek chyba też tam dodam, bo zauważyłem że zbyt często je piszę z palca.

Co do lintera to mam eslint+prettier. Na pewno tu i ówdzie poprawia "" na ' ' + porządkuje wcięcia, ale bardziej się jeszcze nie zagłębiałem, więc doczytam o konfiguracji.

Co do importów:
<img width="625" alt="image" src="https://user-images.githubusercontent.com/38013623/200396765-be1a7da1-0358-4192-a9f8-b055297a23e7.png">

Jeśli dobrze rozumiem, można wrzucić wszystkie importy z całego projektu do jednego pliku z dużym exportem na takiej zasadzie jak na screenie i wszędzie importować { useCokolwiek } from imports.jsx? W sumie sprawdziłem i działa (zdziwko). Dobre, bo niezły tam bajzel się nieraz robi u góry.

Jeszcze szybkie pytanie jeśli można: 
Co do hooka efektu w App.jsx, rzeczywiście bez sensu odpalać to przy każdej zmianie stanu/kontekstu. Czy sama lokalizacja tego hooka w topowym komponencie App.jsx stanowi problem/złą praktykę czy to, że źle określiłem zależność jako cały stan? Zależy mi na tym aby dopilnować aktualizacji localStorage przy zmianie w koszyku (potem chyba to rozszerzę o aktualizację przy logowaniu usera). W każdym razie taka wersja też robi robotę:

```
useEffect(() => {
    console.log('store updated');
    localStorage.setItem('cartItems', JSON.stringify(state.cart.cartItems));
  }, [state.cart.cartItems]);
```

Czy można zostawić ten hook w App.jsx w takiej formie czy lepiej go przenieść do komponentów:
- oddzielny w komponencie albumu (Album.jsx): dodawanie przedmiotu
- oddzielny w komponencie koszyka (Cart.jsx): usuwanie przedmiotu

Jeszcze raz dzięki za feedback. Te rzeczy z useEffect są tego typu, że na początku nie widać problemu a na drugi dzień gdy wraca się do projektu to zakładka ze stroną zajmuje 4gb. 
Pozdrawiam

**Comment by rkoziol** [comment]
> Jeśli dobrze rozumiem, można wrzucić wszystkie importy z całego projektu do jednego pliku z dużym exportem na takiej zasadzie jak na screenie i wszędzie importować { useCokolwiek } from imports.jsx? W sumie sprawdziłem i działa (zdziwko). Dobre, bo niezły tam bajzel się nieraz robi u góry.

Dokładnie jak na screenie, czyli jeśli masz folder components, a w nim pliki
User, Product, Comment, Description, SocialMedia, Gallery etc. to zamiast importować każdy z tych komponentów osobno, warto stosować pliki index, gdzie importujesz wszystkie komponenty z danego foldeu i exportujesz. 

Co do useEffect, to tylko i wyłącznie chodzi o zastosowanie zależności kiedy effect ma się odpalać. Pamiętaj, że w jednym pliku możesz mieć kilka useEffect i jeden z drugim nie musi sobie wchodzić w grę. Ten useEffect, który podlinkowałeś, to dobre rozwiązanie. Zamiast powielać funkcjonalności zamykasz w to parent component i to jest bardzo dobre podejście. 

Gdybyś coś jeszcze potrzebował, dawaj znać, a ja w miarę wolnego czasu i wiedzy na pewno pomogę! :)

**Comment by voinar** [comment]
Dzięki wielkie jeszcze raz. Mam wrażenie, że pod względem jakości rozwiązań projekt już teraz awansował z poziomu Łady do co najmniej VW Golfa III. A to dopiero połowa taska...

**Comment by voinar** [comment]
Cześć Radek,

Wracając do rozmowy, chciałbym poprosić Cię ponownie o feedback. Mam świadomość, że się rozpisałem, więc będę zadowolony nawet jeśli odpowiesz tylko na część pytań. 

Podgląd projektu: 
Portfolio - https://photographer-portfolio-shop-preview.netlify.app/
Sklep - https://photographer-portfolio-shop-preview.netlify.app/sklep

Jeśli chcesz zobaczyć sklep w akcji to można zrobić zakup na próbę. Zamysł biznesowy jest taki, że klient może kupić zdjęcia cyfrowe z danej imprezy. Jest podpięta bramka płatności w trybie sandbox, wysyłają się maile z potwierdzeniem etc. Nie trzeba się logować, wystarczy mail i dowolne imię/nazwisko (tak chciał klient).

Wracając do poprzedniego feedbacku:

- wyeksportowałem zmienne do .env, 
- importy znajdują się w indeksie (src/imports.js)
- powyciągałem często powtarzające się style do pliku src/styles/_variables.scss
- wyczyściłem css z różnych zdublowanych właściwości
- zastosowałem składnię '?.' w obiektach
- poprawiłem funkcje do zapisu z domniemanym(?) zwrotem (implicit return)

Najwięcej pracy było z linterem (od teraz będę robił projekty od początku z aktywnym lintowaniem). Zainstalowalem eslint-config-airbnb + jsx-a11y i przelintowałem cały projekt, żeby było zgodnie z tym zestawem reguł. To wywaliło kilkanaście stron błędów (:D), więc przepisałem kod w całości. Faktycznie lepiej to wygląda. Kilka reguł musiałem wyłączyć, bo tworzyły konflikty z Netlify (np. wymuszone importowanie Reacta na początku każdego pliku wywracało całkiem deploy) albo wymagały zmiany struktury projektu. Na przykład:

1. Indeks z importami (imports.jsx). 
Error: Dependency cycle detected.eslint [import/no-cycle](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-cycle.md)
Na początku wszystko co się dało wrzuciłem do tego pliku żeby mieć jeden import na górze danego komponentu. Okazało się, że niektóre pliki z indeksu importów zawierały wzajemne odniesienia, tj np strona About znajdująca się w imports.js sama również coś importowała z imports, a to wywoływało ww. błąd. Sprobowałem stworzyć oddzielny indeks z komponentami, drugi z rzeczami do bazy danych, ale błąd nadal się pojawiał tylko w innych miejscach. Jest na to jakiś sposób czy to tylko kwestia tej reguły?

2. Optional chaining wspomniane w poprzednim poście. Faktycznie lepiej mieć undefined zamiast błędu, więc zastosowałem to gdzie się dało, ale po włączeniu reguł lintera wyrażenia typu:
`const calculatedAmount = state?.cart?.cartItems?.length * itemPrice;`
musiałem zmienić na zwykłe:
`const calculatedAmount = state.cart.cartItems.length * itemPrice;`
To kwestia samej reguły, która może nie pasuje do tego projektu czy może jest tu jakieś drugie dno?

3. Musiałem zmienić definicje komponentów z funkcji strzałkowych na definiowane przez 'function nazwa() {…}'. W nowszych kursach etc w definicjach komponentów raczej wszędzie widziałem funkcje =>, więc podejrzewam, że albo ten zestaw reguł powstał przed es2105 i teraz stosuje tę regułę na zasadzie legacy, albo czegoś nie rozumiem, bo zgodnie z moim rozumieniem nie ma tu korzyści z tego typu funkcji...

4. Wśród innych reguł które wyłączyłem jest też 'no-underscore-dangle'.
Eslint narzeka na ._ w ścieżkach. Ten ._ pojawia się w ścieżce obiektu który zwraca firebase, więc nie za bardzo mogę z tym coś zrobić poza wyłączeniem reguły:
/* eslint-disable no-underscore-dangle */
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/38013623/208922007-d4abe418-8b47-400f-9187-d0cd72050d0f.png">
Można tak zostawić czy trzeba wymyślać jakieś hacki na to?

5. To tyle jeśli chodzi o lintowanie. Jeśli dobrze rozumiem, to jest to częściowo uznaniowy temat i konkretny styl zależy od decyzji na początkowym etapie projektu. Polecasz może na przyszłość jakieś inne style które są uznawane za 'standard' czy lepiej zostać przy configu airbnb?

6. Czy zostawianie w kodzie zakomentowanych console.logów jest ok? Z brancha produkcyjnego je usunąłem. Czy kod należy czyścić przed każdą publikacją, a wersję z logami np. trzymać na oddzielnym branchu?

7. Ostatnie. Przeglądanie zdjęć w sklepie. Po przejściu do albumu strona wczytuje daną ilość zdjęć, domyślnie 25 – można w pasku u góry zmienić na więcej. Stronicowanie zrobiłem w taki sposób, że kolejne strony wczytują się po odpaleniu funkcji, która pobiera do stanu dany wycinek z pełnej listy zdjęć, czyli np. 0-25, 25-50, 50-75 etc. Mam nadzieję, że tak jest poprawnie.

Kontynuując, użytkownik na desktopie ma możliwość dodania zdjęcia do koszyka po otwarciu podglądu w formie overlaya, który pojawia się po kliknięciu w wybrane zdjęcie. Overlay niczego nowego nie ładuje tylko korzysta z tego samego pliku co miniatura w albumie, czyli takiego który już jest wczytany. Tu mam pytanie. Zdjęcia są już załadowane, lecz overlay zdaje się dość wolno generować dany podgląd. Im więcej zdjęć na stronie tym wolniej to działa. To widać najbardziej gdy nawigujemy strzałkami na overlayu.
<img width="882" alt="image" src="https://user-images.githubusercontent.com/38013623/208917634-5c70ee65-ec89-4c98-97e3-bcec1c5bd6c6.png">
Podgląd: https://photographer-portfolio-shop-preview.netlify.app/album/KETTLEBELL%201000

Na mocnym kompie tego tak bardzo nie widać, ale na starszym muli potężnie i na produkcji dałem limit 40 fotek na stronę. W wersji mobilnej nie ma overlaya, więc tam można ładować bez problemu po 100+ zdjęć i nic nie szarpie. 

Miałem podejrzenie, że wynika to z tego, że za każdym przejściem do kolejnego zdjęcia odświeża się cały kontekst, więc z tego (src/contexts/Store.js):
<img width="864" alt="image" src="https://user-images.githubusercontent.com/38013623/208735345-b9ab9877-c8ef-4dba-b71e-60821a99a57d.png">
zrobiłem to:
<img width="812" alt="image" src="https://user-images.githubusercontent.com/38013623/208737254-b04c7299-5191-483a-b258-bb2870792977.png">
...ale stan i tak odświeża się cały po wyświetleniu kolejnego obrazka, więc useMemo nie pomaga. Może trzeba wyrzucić tę listę z obrazkami w overlayu do oddzielnego kontekstu? Czy może problem leży gdzie indziej?

8. Gdybyś widział w kodzie jakieś słabe/rażące praktyki to też byłbym wdzięczny za zasygnalizowanie...

Dzięki za poświęcony czas. Mam świadomość, że trochę tego jest więc tak jak napisałem na początku - nawet odpowiedzi na wybrane akapity będą dla mnie na wagę złota :)

Pozdrawiam

**Comment by rkoziol** [comment]
Importy - troszke over-engineering IMO, albo ja sam sie zle wyrazilem na poczatku. Generalnie zamysl importow jest taki (w wiekszosci projektow), 
ze gdy masz katalog projektowy wygladajacy w ten sposob:
>src
>> components
>> services
>>> user.service
>>> post.service

>> utils

to np gdy chcesz skorzystac z servicu w jakims komponencie A, to robisz to w taki sposob:

`import { postUser } from '@services'` a nie`: import { postUser } from '../../services/post.service'`, mam nadzieje, ze jest to dla Ciebie zrozumiale, jesli nie, to bede probowal to wyjasnic jeszcze w inny sposob. :)


----

wyeksponowanie wspolnego pliku do variables scss - swietny krok i bardzo dobrze zrobione. Widze, ze masz tez styl nazewnictwa, super.

Co zauwazylem, to plik style.css.map - generalnie staraj sie unikac przechowywania takich plikow w kodzie zrodlowym swojego projektu, takie pliki powinny byc tylko w paczce wynikowej danej aplikacji.

----

Linter, super sprawa i tak jak wspomniales, warto uzywac go od pierwszych chwil juz w projekcie. Sporo Ci ulatwi pozniej pracy, gdy projekt bedzie juz na zaawansowanym etapie, podobnie jak Twoj.

----

Error z lintera dla Error: Dependency cycle detected.eslint import/no-cycle jest trafny i nie warto go obchodzic w jakikolwiek sposob. 
Generalnie importow nie ma sie co bac, jesli bedzie ich duzo, trudno. Najwazniejsze to zeby zachowac priorytet importow (na gorze zewnetrzne biblioteki, pozniej reuzywalne skrypty wlasne i na koncu cos, co tylko jest w tym komponencie ale jest w innym pliku (np style, jakies handlersy etc.)

----

Optional chaining - w przypadku, jesli w Twoim kodzie jest zadeklarowany jakis default state/value etc., to nie musisz stosowac optionala.

----

function nazwa() {…} - bardzo dziwne zachowanie. Probowales eslinta tylko z defaultowymi zasadami? Bez instalowania zewnetrznych paczek?

---- 

no-underscore-dangle - no coz, czasami trzeba dodac wyjatek, to prawda. Natomiast w JS'ie czesto _ przed jakims propertiesem oznacza, ze lepiej do niego sie nie odnosic i jest on private dla danego obiektu.

----

ad. 5 - Ja najczesciej korzystam z defaultowego ktore sam eslint dostarcza. https://github.com/rkoziol/react-typescript-jest-boilerplate tutaj mozesz sobie podpatrzec jak wyglada moj stack wyjsciowy jesli chodzi o projekt reactowy. 
Jest tez dokladnie jak mowisz. Styl projektu zalezy w glownej mierze od zalozen poczatkowych zespolu. Co dla jednych bedzie wygodne, dla innych bedzie slabe. Najwazniejsze, zeby TObie sie dobrze z kodem wspolpracowalo - wiadomo, 
nie mozna odwalac po calosci, skoro pozniej bedzie to jako Twoja wizytowka, natomiast nie ma co tez popadac w skrajnosci w skrajnosc. Wiec wyjatki od jakis zasad, ustawienie swoich regul do jakis przypadkow jest jak najbardziej ok.

----

ad. 6 - Bardzo dobra praktyka jest wywalanie console.log'ow - chyba, ze mowia o jakims waznym fakcie np zalogowanie do serwera baz danych itp. W innych przypadkach (np debugowania) to sa do wywalenia.
Jesli nie chcesz robic tego manualnie, to do webpacka sa specjalne pluginy, ktore umozliwia Ci automatyzacje tego i wywalenie za Ciebie. :)

----

ad. 7 - Na pierwszy rzut trafil sei blad. Wszedlem w zakladke "Biegam i wspieram" i mimo, ze wyswietlilo mi wszystkie zdjecia, to nadal mam mozliwosc klikniecia strzalki w bok. Generalnie ladowanie tylko czesci danych, ktore uzytkownik widzi na pierwszy rzut, to suepr podejscie.
Lazy loading / Infinite scroll etc. czyli mechanizmy, ktore sa w social mediach, idealnie pomagaja w optymalizacji i performencie aplikacji. 

----

Tak, zauwazylem, ze z aplikacja jest cos nie tak w momencie kiedy ma sporo zdjec zaladowanych + modal. Nawet dzialanie przegladarki zwalnia i debugowanie kodu jest uciazliwe. W momencie kiedy modal/overlay jest zmakniety, wszystko wraca do normy. Na bank wina lezy po stronie modala.


ok, teraz kod:

- atoms - w tym folderze trzymasz reuzywalne komponenty? W projektach najczesciej spotyka sie nazewnictwo "common" lub "shared"
- components/styles - ja wrzucilbym wszystkie /styles do jednego folderu nadrzengoe styles. Teraz jest tak, ze troche masz w glownym src a troche pochowane po komponentach. Moze byc mylace, jednak jesli Tobie to odpowiada, to tylko wkestia gustu. :)
- https://github.com/voinar/mern_photographer-portfolio-ecommerce-site/blob/master/photographer-portfolio-frontend/src/routes/RoutesContainer.jsx#L19 - kurde, jestem zdziwiony ze nie mozesz tutaj zrobic czegos takiego:

export default() => (
	<Routes>
      <Route path="/" element={<SectionWelcome />} />
      <Route path="/witaj" element={<SectionWelcome />} />
      <Route path="/portfolio/:category" element={<SectionContent />} />
....
);

Dane takie jak:
const TRACKING_ID = 'G-5EQQ443LWM'; // OUR_TRACKING_ID
const facebookPixelId = '5969461459733693';

itp. lepiej wrzucac do .env

https://github.com/voinar/mern_photographer-portfolio-ecommerce-site/blob/master/photographer-portfolio-frontend/src/components/AlbumImage.jsx#L55 wartosci liczbowe/tekstowe itd zawsze umieszczaj w stalych, ktore dobrze nazwiesz. Raz, ze bedzie dla Ciebie to latwiej pozniej utrzymac, a dwa ktos kiedys
biorac projekt po Tobie szybciej zrozumie skad sie tutaj wzielo cos takiego i dlaczego.

https://github.com/voinar/mern_photographer-portfolio-ecommerce-site/blob/master/photographer-portfolio-frontend/src/components/Footer.jsx#L17 - dlaczego tutaj od razu nie zrobic return? 

https://github.com/voinar/mern_photographer-portfolio-ecommerce-site/blob/master/photographer-portfolio-frontend/src/components/Navbar.jsx#L37 - jesli juz masz odwolanie do routingu, to staraj sie trzymac ich adresy w jednym pliku, tak, by w czasie zmiany rotuingu byla potrzeba tylko zmiana jednego pliku a nie skakania po calym projekcie.

https://github.com/voinar/mern_photographer-portfolio-ecommerce-site/blob/master/photographer-portfolio-frontend/src/components/OrderForm.jsx#L95 - ten regex sluzy Ci do czego? Warto to nazwac, np regex do liczb nazwalbym "NUM_REGEX" i juz koeljna osoba wie, co ten regex +/- robi.

https://github.com/voinar/mern_photographer-portfolio-ecommerce-site/blob/master/photographer-portfolio-frontend/src/components/OrderForm.jsx#L114 - dlaczego 2 i 30? tak jak wczesniej pisalem, wszystkei tego typu sprawy, do stalej + dobrze ja nazwac. Niech sie to samo dokumentuje

https://github.com/voinar/mern_photographer-portfolio-ecommerce-site/blob/master/photographer-portfolio-frontend/src/components/OrderForm.jsx#L170 - to cale mozesz smialo zamknac w jakims serwisie i wyniesc do innego pliku, w koncu to juz komunikacja


To tak po przeczytaniu i ogladnieciu kodu. W razie czego, pozostaje do dyspozycji :)

**Comment by rkoziol** [comment]
Zamykam, w razie kolejnych dyskusji, otworz prosze nowy watek albo wrzuc notke na telegrama
